version: "3.8"

services:
  # PostgreSQL DB
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookpoll
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # auth-service
  auth-service:
    image: bodibo/auth-service:latest
    build: ./auth-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/bookpoll
      JWT_SECRET: bookpoll-super-secret-key-2026
    depends_on:
      - postgres

  # book-service
  book-service:
    image: bodibo/book-service:latest
    build: ./book-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/bookpoll
      AUTH_SERVICE_URL: http://auth-service:8001
    depends_on:
      - postgres

  # vote-service
  vote-service:
    image: bodibo/vote-service:latest
    build: ./vote-service
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/bookpoll
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
      - redis

  # notify-service
  notify-service:
    image: bodibo/notify-service:latest
    build: ./notify-service
    ports:
      - "8004:8004"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
  redis_data: