apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bookpoll
data:
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "bookpoll"
  DATABASE_URL: "postgresql://bookpoll:bookpoll1234@postgres:5432/bookpoll"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: bookpoll
type: Opaque
stringData:
  DB_USER: bookpoll
  DB_PASSWORD: bookpoll1234
  SECRET_KEY: mysecretkey123
  DATABASE_URL: "postgresql://bookpoll:bookpoll1234@postgres:5432/bookpoll"