# app-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: bookpoll
type: Opaque
stringData:
  DB_USER: bookpoll
  DB_PASSWORD: bookpoll1234
  SECRET_KEY: mysecretkey123
  JWT_SECRET: "fallback_secret_key_for_bookpoll_2026"
  DATABASE_URL: "postgresql://bookpoll:bookpoll1234@postgres-service:5432/postgres"