apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookpoll
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dibo-world/bookpoll
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bookpoll
  syncPolicy:
    automated:
      prune: true
      selfHeal: true