apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bookpoll
type: Opaque
stringData:
  POSTGRES_USER: bookpoll
  POSTGRES_PASSWORD: bookpoll1234
  POSTGRES_DB: bookpoll
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: bookpoll
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: bookpoll
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None