apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookpoll-sa
  namespace: bookpoll
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bookpoll-role
  namespace: bookpoll
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bookpoll-rolebinding
  namespace: bookpoll
subjects:
  - kind: ServiceAccount
    name: bookpoll-sa
    namespace: bookpoll
roleRef:
  kind: Role
  name: bookpoll-role
  apiGroup: rbac.authorization.k8s.io